#define TYPE_IPV6 0x86DD

#define SIP_META_ETHERTYPE 0xEA01
#define HOP_MAC_LOAD_ETHERTYPE 0xEA02
#define HOP_MAC_RESULT_ETHERTYPE 0xEA03
#define AUTH_MAC_LOAD_ETHERTYPE 0xEA04
#define AUTH_MAC_RESULT_ETHERTYPE 0xEA05

#define PORT_HASH_TO_EPIC 1
#define PORT_EPIC_TO_HASH 2